[package]
name = "madsim_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
madsim = "0.2"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1.0", features = ["full"] }

[[bin]]
name = "raft_simulation_test"
path = "src/main.rs"